=== SaraOrtegaHdez13/40260/xml/xml-00.dtd
<?xml version="1.0" encoding="UTF-8">
<!ELEMENT direccion (nombreCompleto, correo, telefono, cumple)>
<!ELEMENT nombreCompleto(nombre, apellido)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT correo (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT cumple(dia, mes, anio)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT anio (#PCDATA)>

=== SaraOrtegaHdez13/40260/xml/xml-00.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE direccion SYSTEM "xml-00.dtd">
<direccion>
    <nombreCompleto>
        <nombre>Sara</nombre>
        <apellido>Ortega</apellido>
    </nombreCompleto>

    <correo>SaraOrtegaHdez13@gmail.com</correo>
    <telefono>2321130770</telefono>

    <cumple>
        <dia>13</dia>
        <mes>03</mes>
        <anio>2002</anio>
    </cumple>
</direccion>
